---
title: "code for report"
author: "Dongyue Xie"
date: "2018-12-06"
output: workflowr::wflow_html
---

# Plots

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE)
```

```{r}
library(lme4)
library(MCMCglmm)
datax=read.csv('/Users/dongyue/Documents/phd y1t1/data analysis/archive_edi/Reich2018NaturePaperDataAug2018.csv')
datax=datax[-c(25,26,580),]
colnames(datax)[3]='trt'
colnames(datax)[4]='plot'
colnames(datax)[13]='water'
colnames(datax)[10]='ps'
datax$plot=factor(datax$plot)

species=c("aceru", "acesa", 'betpa', "quema", "queru", 'poptr', 'rhaca', 'abiba', 'picgl', "pinba", "pinst")

needle=c('abiba','picgl','pinba','pinst')
datax$species2=factor(ifelse(datax$species %in% needle,'needle','broad'))


##plot boxplot of trt vs ps acroos species*site

par(mfrow=c(2,3))
boxplot(ps~trt,data=datax[datax$site=='hwrc'&datax$species2=='broad',],
        main='HWRC-broad',ylab='Photosynthesis')
boxplot(ps~trt,data=datax[datax$site=='hwrc'&datax$species2=='needle',],
        main='HWRC-needle',ylab='Photosynthesis')
boxplot(water~trt,data=datax[datax$site=='hwrc',],
        main='HWRC',ylab='soil water')


boxplot(ps~trt,data=datax[datax$site=='cfc'&datax$species2=='broad',],
        main='CFC-broad',ylab='Photosynthesis')
boxplot(ps~trt,data=datax[datax$site=='cfc'&datax$species2=='needle',],
        main='CFC-needle',ylab='Photosynthesis')


#par(mfrow=c(2,2))
#boxplot(gs~trt,data=datax[datax$site=='hwrc'&datax$species2=='broad',],
#        main='HWRC-broadleaf',ylab='diffusive conductance')
#boxplot(gs~trt,data=datax[datax$site=='hwrc'&datax$species2=='needle',],
#        main='HWRC-needleleaf',ylab='diffusive conductance')
#boxplot(gs~trt,data=datax[datax$site=='cfc'&datax$species2=='broad',],
#        main='CFC-broadleaf',ylab='diffusive conductance')
#boxplot(gs~trt,data=datax[datax$site=='cfc'&datax$species2=='needle',],
#        main='CFC-needleleaf',ylab='diffusive conductance')


#par(mfrow=c(1,2))


boxplot(water~trt,data=datax[datax$site=='cfc',],
        main='CFC',ylab='soil water')

```

```{r,fig.width=10,fig.height=10}
##########################
#PLOT OF photosynthesis vs vwc
species=c("aceru", "acesa", 'betpa', "quema", "queru", 'poptr', 'rhaca', 'abiba', 'picgl', "pinba", "pinst")

#datax=na.omit(datax)
par(mfrow=c(4,3))
for (sp in species) {
  dat=datax[datax$species==sp,]
  amb=lm(ps~water,data=dat[dat$trt=='ambient',])
  
  warm=lm(ps~water,data=dat[dat$trt=='warmed',])
  plot(ps~water,data=dat,main=sp,ylab='Photosynthesis',
       col=ifelse(dat$trt=='ambient',4,2))
  xx=seq(0.05,0.27,length.out = 100)
  lines(amb$model$water,amb$fitted.values,col=4,lwd=2)
  lines(warm$model$water,warm$fitted.values,col=2,lwd=2)
}

#plot of species2: ps vs water
```

```{r,fig.width=6,fig.height=4}
species2=c('broad','needle')
par(mfcol=c(2,3))

for (sp in species2) {
  dat=datax[datax$species2==sp,]
  amb=lm(ps~water,data=dat[dat$trt=='ambient',])
  
  warm=lm(ps~water,data=dat[dat$trt=='warmed',])
  plot(ps~water,data=dat,main=sp,ylab='photosynthesis',
       col=ifelse(dat$trt=='ambient',4,2),ylim=c(-1,35),xlab='soil water content')
  xx=seq(0.05,0.27,length.out = 100)
  lines(amb$model$water,amb$fitted.values,col=4,lwd=2)
  lines(warm$model$water,warm$fitted.values,col=2,lwd=2)
  legend('topleft',c('ambient','warmed'),lty=c(1,1),col=c(4,2))
}

for (sp in species2) {
  dat=datax[datax$species2==sp,]
  amb=lm(gs~water,data=dat[dat$trt=='ambient',])
  
  warm=lm(gs~water,data=dat[dat$trt=='warmed',])
  plot(gs~water,data=dat,main=sp,ylab='leaf diffusive conductance',
       col=ifelse(dat$trt=='ambient',4,2),ylim=c(0,0.9),xlab='soil water content')
  xx=seq(0.05,0.27,length.out = 100)
  lines(amb$model$water,amb$fitted.values,col=4,lwd=2)
  lines(warm$model$water,warm$fitted.values,col=2,lwd=2)
  legend('topleft',c('ambient','warmed'),lty=c(1,1),col=c(4,2))
}


pp=levels(datax$plot)
ll=lm(ps~water,data=datax[datax$plot==pp[1],])
plot(ll$model$water,ll$fitted.values,type='l',ylim=c(4,17),xlim=c(0.05,0.27),col=2,ylab='Photosynthesis',xlab='soil water content',
     main='plot')
legend('bottomright',c('ambient','warmed'),lty=c(1,1),col=c(4,2))

for (p in pp[-1]) {
    ll=lm(ps~water,data=datax[datax$plot==p,])
    if(datax[datax$plot==p,][1,]$trt=='ambient'){cc=4}else{cc=2}
    lines(ll$model$water,ll$fitted.values,col=cc)
}

pp=levels(datax$block)
ll=lm(ps~water,data=datax[datax$block==pp[1],])
plot(ll$model$water,ll$fitted.values,type='l',ylim=c(4,17),xlim=c(0.05,0.27),col=1,ylab='Photosynthesis',xlab='soil water content',
     main='block')


for (p in pp[-1]) {
  ll=lm(ps~water,data=datax[datax$block==p,])
  
  lines(ll$model$water,ll$fitted.values,col=1)
}

```


```{r}
datas=na.omit(datax)
datas$ci=datas$ci
#year:doy as factor
datas$day=factor(datas$year):factor(datas$doy)
datas$day=factor(datas$day)
```


# Model 1, 2

```{r}
#after some model selection...
mod1=lmer(ps~trt+species2+water+trt:species2+trt:water+(1|day)+(1|block)+(1|plot),data=datas)
#drop1(mod1ss,test='Chisq')
ss.mod1=summary(mod1)
mod2=lmer(gs~trt+species2+water+trt:species2+trt:water+(1|day)+(1|block)+(1|plot),data=datas)
#drop1(mod1ss,test='Chisq')
ss.mod2=summary(mod2)
```

Coefficients, Standard deviation of random components:

```{r}
round(ss.mod1$coefficients,2)
round(c(sqrt(unlist(ss.mod1$varcor)),ss.mod1$sigma),2)
```

```{r}
round(ss.mod2$coefficients,2)
round(c(sqrt(unlist(ss.mod2$varcor)),ss.mod2$sigma),2)
```


# Model 3: species random

```{r}
mod3=lmer(ps~trt*(water+ci)+VPG+(1|day)+(1|block)+(1|plot)+(1|species2),data=datas)
ss.mod3=summary(mod3)
```

```{r}
round(ss.mod3$coefficients,2)
round(c(sqrt(unlist(ss.mod3$varcor)),ss.mod3$sigma),2)
```

## Conditional independence

```{r}
mm=lmer(ps~water+trt+(1|day)+(1|block)+(1|plot)+(1|species2),data=datas,REML = 0)
round(drop1(mm,test='Chisq'),2)
```

```{r}
mm=lmer(gs~water+trt+(1|day)+(1|block)+(1|plot)+(1|species2),data=datas,REML = 0)
round(drop1(mm,test='Chisq'),2)
```

## bivariate  models


###Needle leaf:

```{r}

prior2=list(R = list(V = diag(2),nu=1),
               G=list(G1=list(V=diag(2),nu=1,alpha.mu=rep(0,2),alpha.V=diag(2)*1e3),
                  G2=list(V=diag(2),nu=1,alpha.mu=rep(0,2),alpha.V=diag(2)*1e3),
                  G3=list(V=diag(2),nu=1,alpha.mu=rep(0,2),alpha.V=diag(2)*1e3)
                  ))
set.seed(1234)
mulmod1=MCMCglmm(cbind(ps,water)~trait*trt,
                      random=~us(trait):day+idh(trait):block+
                          idh(trait):plot,rcov=~idh(trait):units,
                      prior = prior2,
                      family = c("gaussian","gaussian"),
                      data=datas[datas$species2=='needle',],nitt=15000,burnin = 5000,thin = 10,verbose = F)
```

```{r}
round(summary(mulmod1)$solutions[,1:3],3)
```

Cov and Cor - day

```{r}
poster.mode=apply(mulmod1$VCV, 2, posterior.mode)
cov.day=matrix(poster.mode[1:4],2,2)
rownames(cov.day)=c('PS','Water')
colnames(cov.day)=c('PS','Water')
round(cov.day,3)
round(cov2cor(cov.day),3)
```

Sd: block, plot, random error

```{r}
knitr::asis_output("\\scriptsize")
rrn=rbind(round(sqrt(poster.mode[5:6]),2),
round(sqrt(poster.mode[7:8]),3),
round(sqrt(poster.mode[9:10]),2))
rownames(rrn)=c('block','plot','error')
colnames(rrn)=c('PS','Water')
rrn
```


### broad-leaf

```{r}
prior2=list(R = list(V = diag(2),nu=1),
               G=list(G1=list(V=diag(2),nu=1,alpha.mu=rep(0,2),alpha.V=diag(2)*1e3),
                  G2=list(V=diag(2),nu=1,alpha.mu=rep(0,2),alpha.V=diag(2)*1e3),
                  G3=list(V=diag(2),nu=1,alpha.mu=rep(0,2),alpha.V=diag(2)*1e3)
                  ))
set.seed(1234)
mulmod2=MCMCglmm(cbind(ps,water)~trait*trt,
                      random=~us(trait):day+idh(trait):block+
                          idh(trait):plot,rcov=~idh(trait):units,
                      prior = prior2,
                      family = c("gaussian","gaussian"),
                      data=datas[datas$species2=='broad',],nitt=15000,burnin = 5000,thin = 10,verbose = F)

```

Fixed effects:

```{r}
round(summary(mulmod2)$solutions[,1:3],3)
```



Cov and Cor - day

```{r}
poster.mode=apply(mulmod2$VCV, 2, posterior.mode)
cov.day=matrix(poster.mode[1:4],2,2)
rownames(cov.day)=c('PS','Water')
colnames(cov.day)=c('PS','Water')
round(cov.day,3)
round(cov2cor(cov.day),3)
```

Sd: block, plot and random error

```{r}
rrb=rbind(round(sqrt(poster.mode[5:6]),2),
round(sqrt(poster.mode[7:8]),3),
round(sqrt(poster.mode[9:10]),2))
rownames(rrb)=c('block','plot','error')
colnames(rrb)=c('PS','Water')
rrb
```
